services:
  redis:
    image: redis:alpine
    command: redis-server
    restart: always
    ports:
      - '6379:6379'
  server:
    build: .
    depends_on:
      - redis
    restart: always
    ports:
      - '3000:3000'
    environment:
      GENIUS_TOKEN: ${GENIUS_TOKEN}
      REDIS_TLS_URL: redis://redis:6379
      TLS: false
    volumes:
      - .:/app
